"""Generate lightweight delivery manifests for report assets."""

from __future__ import annotations

from pathlib import Path


def _latex_escape(text: str) -> str:
    return (
        text.replace("\\", r"\textbackslash{}")
        .replace("_", r"\_")
        .replace("&", r"\&")
        .replace("%", r"\%")
        .replace("#", r"\#")
    )


def _relative_names(root: Path, pattern: str) -> list[str]:
    return sorted(path.relative_to(root).as_posix() for path in root.glob(pattern) if path.is_file())


def generate_asset_manifest(root: str | Path) -> dict[str, int]:
    root = Path(root)
    figures_png = _relative_names(root, "figures/fig*.png")
    figures_pdf = _relative_names(root, "figures/fig*.pdf")
    result_csv = _relative_names(root, "results/**/*.csv")

    docs_dir = root / "docs"
    docs_dir.mkdir(parents=True, exist_ok=True)
    tables_dir = root / "overleaf_report" / "tables"
    tables_dir.mkdir(parents=True, exist_ok=True)

    md_lines = [
        "# Results Asset Manifest",
        "",
        "This file is generated by `python -m src.run_all`.",
        "",
        f"- PNG figures: {len(figures_png)}",
        f"- PDF figures: {len(figures_pdf)}",
        f"- CSV result tables: {len(result_csv)}",
        "",
        "## Figures",
        "",
        *[f"- `{name}`" for name in figures_png],
        "",
        "## Result CSV Files",
        "",
        *[f"- `{name}`" for name in result_csv],
        "",
    ]
    (docs_dir / "results_asset_manifest.md").write_text("\n".join(md_lines), encoding="utf-8")

    tex_lines = [
        r"\begin{tabular}{llr}",
        r"\toprule",
        r"Type & Location & Count \\",
        r"\midrule",
        rf"Figures & \texttt{{figures/*.png}} & {len(figures_png)} \\",
        rf"Figures & \texttt{{figures/*.pdf}} & {len(figures_pdf)} \\",
        rf"CSV results & \texttt{{results/**/*.csv}} & {len(result_csv)} \\",
        r"\bottomrule",
        r"\end{tabular}",
        "",
        r"\vspace{0.5em}",
        "",
        r"\noindent Key result files: "
        + ", ".join(rf"\texttt{{{_latex_escape(Path(name).name)}}}" for name in result_csv[:8])
        + (r"." if result_csv else r"none."),
        "",
    ]
    (tables_dir / "asset_manifest.tex").write_text("\n".join(tex_lines), encoding="utf-8")

    return {"figures_png": len(figures_png), "figures_pdf": len(figures_pdf), "results_csv": len(result_csv)}
